spring.application.name=nft-gestor

spring.profiles.active=prod
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=fftgestor@gmail.com
spring.mail.password=xyrl jhzs jlty gwqh
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
